name: Deploy to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'terraform/aws/**'

env:
  APP_NAME: aws-mcapp
  REGION: us-west-2
  REPO_NAME: aws-mcapp-repo
  SERVICE_NAME: aws-mcapp-api
  CLUSTER_NAME: aws-mcapp-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.REPO_NAME }}:${{ github.sha }}"
          LATEST_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.REPO_NAME }}:latest"
          
          docker build -t $IMAGE -f app/backend/Dockerfile app/backend
          docker tag $IMAGE $LATEST_IMAGE
          
          docker push $IMAGE
          docker push $LATEST_IMAGE

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} \
            --service ${{ env.SERVICE_NAME }} \
            --force-new-deployment \
            --region ${{ env.REGION }}